# Generated by Django 4.2.10 on 2024-03-07 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alunos', '0009_remove_aluno_orientador1_remove_aluno_orientador2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('orientado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='alunos.aluno')),
            ],
        ),
    ]
