# Generated by Django 4.2.10 on 2024-03-07 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0011_alter_aluno_orientadores'),
        ('docentes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='docente',
            name='orientado',
        ),
        migrations.AddField(
            model_name='docente',
            name='orientados',
            field=models.ManyToManyField(related_name='docentes_orientadores', to='alunos.aluno'),
        ),
        migrations.AddField(
            model_name='docente',
            name='sobrenome',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
