# Generated by Django 4.2.10 on 2024-03-07 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0011_alter_aluno_orientadores'),
        ('docentes', '0003_alter_docente_orientados'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docente',
            name='orientados',
            field=models.ManyToManyField(blank=True, related_name='docentes_orientadores', to='alunos.aluno'),
        ),
    ]
