# Generated by Django 4.2.10 on 2024-03-11 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docentes', '0004_alter_docente_orientados'),
    ]

    operations = [
        migrations.AddField(
            model_name='docente',
            name='email',
            field=models.EmailField(max_length=255, null=True),
        ),
    ]
