# Generated by Django 4.2.10 on 2024-02-20 01:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('turmas', '0008_remove_turma_data_de_criação_turma_data_de_criacao'),
        ('alunos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turmas.turma'),
        ),
    ]
