# Generated by Django 4.2.10 on 2024-02-21 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0003_alter_aluno_curso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='orientador2',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
