# Generated by Django 4.2.10 on 2024-02-21 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0004_alter_aluno_orientador2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='orientador2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
