# Generated by Django 4.2.10 on 2024-02-28 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0006_aluno_email_aluno_matricula'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exclusao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exclusao', models.CharField(choices=[('jubilado', 'Jubilado'), ('trancamento', 'Tracamento'), ('exclusao', 'Exclusão definitiva')], max_length=25)),
                ('aluno', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='alunos.aluno')),
            ],
        ),
    ]
