# Generated by Django 4.2.10 on 2024-02-28 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0007_exclusao'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Exclusao',
        ),
    ]
