# Generated by Django 4.2.10 on 2024-03-07 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0008_delete_exclusao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='orientador1',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='orientador2',
        ),
    ]
