# Generated by Django 4.2.10 on 2024-03-07 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docentes', '0001_initial'),
        ('alunos', '0009_remove_aluno_orientador1_remove_aluno_orientador2'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='orientadores',
            field=models.ManyToManyField(related_name='orientados', to='docentes.docente'),
        ),
    ]
