# Generated by Django 4.2.10 on 2024-03-07 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docentes', '0001_initial'),
        ('alunos', '0010_aluno_orientadores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='orientadores',
            field=models.ManyToManyField(related_name='alunos_orientados', to='docentes.docente'),
        ),
    ]
