# Generated by Django 4.2.10 on 2024-03-13 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0011_alter_aluno_orientadores'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='artigo',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='aluno',
            name='defesa',
            field=models.BooleanField(default=False),
        ),
    ]
