# Generated by Django 4.2.10 on 2024-03-13 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0012_aluno_artigo_aluno_defesa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='defesa',
            field=models.BooleanField(),
        ),
    ]
