# Generated by Django 4.2.10 on 2024-03-13 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0016_alter_aluno_artigo_alter_aluno_obs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='artigo',
            field=models.URLField(blank=True, error_messages={'required': 'Link cannot be left blank.'}, max_length=400, null=True),
        ),
    ]
