# Generated by Django 4.2.10 on 2024-03-13 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0017_alter_aluno_artigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='artigo',
            field=models.URLField(blank=True, max_length=400, null=True),
        ),
    ]
