# Generated by Django 4.2.10 on 2024-03-14 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0018_alter_aluno_artigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='data_defesa',
            field=models.DateField(null=True),
        ),
    ]
