# Generated by Django 4.2.10 on 2024-03-19 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0019_aluno_data_defesa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='defesa',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='obs',
            field=models.TextField(blank=True, max_length=255),
        ),
    ]
