# Generated by Django 4.2.9 on 2024-03-19 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0020_alter_aluno_defesa_alter_aluno_obs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='data_defesa',
            field=models.DateField(blank=True, null=True),
        ),
    ]
