# Generated by Django 4.2.9 on 2024-03-21 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0021_alter_aluno_data_defesa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='bolsista',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='defesa',
            field=models.BooleanField(blank=True),
        ),
    ]
