# Generated by Django 4.2.9 on 2024-03-21 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0022_alter_aluno_bolsista_alter_aluno_defesa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='artigo',
            field=models.URLField(blank=True, max_length=400),
        ),
    ]
