# Generated by Django 4.2.11 on 2024-04-03 23:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0023_alter_aluno_artigo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Desistente',
            fields=[
                ('aluno_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='alunos.aluno')),
                ('motivo', models.CharField(max_length=255)),
                ('data_desistencia', models.DateField(auto_now_add=True)),
            ],
            bases=('alunos.aluno',),
        ),
        migrations.CreateModel(
            name='Jubilado',
            fields=[
                ('aluno_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='alunos.aluno')),
                ('motivo', models.CharField(max_length=255)),
                ('data_jubilamento', models.DateField(auto_now_add=True)),
            ],
            bases=('alunos.aluno',),
        ),
        migrations.CreateModel(
            name='Trancamento',
            fields=[
                ('aluno_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='alunos.aluno')),
                ('motivo', models.CharField(blank=True, max_length=255)),
                ('data_trancamento', models.DateField(auto_now_add=True)),
                ('semestre_retorno', models.DateField(blank=True, max_length=50)),
            ],
            bases=('alunos.aluno',),
        ),
    ]
