# Generated by Django 4.2.11 on 2024-04-17 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0023_alter_aluno_artigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='motivo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aluno',
            name='situacao',
            field=models.CharField(choices=[('E', 'Em andamento'), ('J', 'Jubilado'), ('D', 'Desistência'), ('T', 'Trancamento')], max_length=2, null=True),
        ),
    ]
