# Generated by Django 4.2.11 on 2024-04-17 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0024_aluno_motivo_aluno_situacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='situacao',
            field=models.CharField(choices=[('E', 'Em andamento'), ('J', 'Jubilado'), ('D', 'Desistência'), ('T', 'Trancamento'), ('C', 'Concluído')], max_length=2, null=True),
        ),
    ]
