# Generated by Django 4.2.11 on 2024-04-10 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0024_desistente_jubilado_trancamento'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Desistente',
        ),
    ]
