# Generated by Django 4.2.11 on 2024-04-17 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0025_alter_aluno_situacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='situacao',
            field=models.CharField(choices=[('E', 'Em andamento'), ('J', 'Jubilado'), ('D', 'Desistência'), ('T', 'Trancamento'), ('C', 'Concluído')], default='E', max_length=2, null=True),
        ),
    ]
