# Generated by Django 4.2.11 on 2024-04-10 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0025_delete_desistente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Desistente',
            fields=[
                ('aluno_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='alunos.aluno')),
                ('motivo', models.CharField(max_length=255)),
                ('data_desistencia', models.DateField(auto_now_add=True)),
            ],
            bases=('alunos.aluno',),
        ),
    ]
