# Generated by Django 4.2.11 on 2024-04-17 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0027_ativos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='desistente',
            name='aluno_ptr',
        ),
        migrations.RemoveField(
            model_name='jubilado',
            name='aluno_ptr',
        ),
        migrations.RemoveField(
            model_name='trancamento',
            name='aluno_ptr',
        ),
        migrations.AddField(
            model_name='aluno',
            name='motivo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aluno',
            name='situacao',
            field=models.CharField(choices=[('E', 'Em andamento'), ('J', 'Jubilado'), ('D', 'Desistência'), ('T', 'Trancamento')], max_length=2, null=True),
        ),
        migrations.DeleteModel(
            name='Ativos',
        ),
        migrations.DeleteModel(
            name='Desistente',
        ),
        migrations.DeleteModel(
            name='Jubilado',
        ),
        migrations.DeleteModel(
            name='Trancamento',
        ),
    ]
