# Generated by Django 4.2.11 on 2024-07-08 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0028_alter_aluno_bolsista'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aluno',
            old_name='curso',
            new_name='turma',
        ),
    ]
