# Generated by Django 4.2.11 on 2024-07-08 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0029_rename_curso_aluno_turma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='artigo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
