# Generated by Django 4.2.11 on 2024-07-11 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0030_alter_aluno_artigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='bolsa',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='bolsista',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
