# Generated by Django 4.2.11 on 2024-07-11 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0031_aluno_bolsa_alter_aluno_bolsista'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='academico',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
