# Generated by Django 4.2.14 on 2024-07-29 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0033_rename_bolsista_aluno_eh_bolsista_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='eh_bolsista',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
