# Generated by Django 5.0.1 on 2024-01-25 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turmas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='turma',
            name='dataInicio',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='turma',
            name='vagas',
            field=models.IntegerField(null=True),
        ),
    ]
