# Generated by Django 5.0.1 on 2024-01-29 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turmas', '0002_turma_datainicio_turma_vagas'),
    ]

    operations = [
        migrations.AddField(
            model_name='turma',
            name='dataCreation',
            field=models.DateField(null=True),
        ),
    ]
