# Generated by Django 5.0.1 on 2024-01-29 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turmas', '0003_turma_datacreation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='turma',
            old_name='dataCreation',
            new_name='data_de_criação',
        ),
    ]
