# Generated by Django 5.0.1 on 2024-01-29 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turmas', '0004_rename_datacreation_turma_data_de_criação'),
    ]

    operations = [
        migrations.RenameField(
            model_name='turma',
            old_name='dataInicio',
            new_name='data_de_inicio',
        ),
    ]
