# Generated by Django 5.0.1 on 2024-01-29 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turmas', '0005_rename_datainicio_turma_data_de_inicio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='turma',
            old_name='data_de_inicio',
            new_name='data_de_início',
        ),
    ]
