# Generated by Django 4.2.10 on 2024-02-19 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turmas', '0006_rename_data_de_inicio_turma_data_de_início'),
    ]

    operations = [
        migrations.RenameField(
            model_name='turma',
            old_name='data_de_início',
            new_name='data_de_inicio',
        ),
    ]
