# Generated by Django 4.2.10 on 2024-02-20 01:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('turmas', '0007_rename_data_de_início_turma_data_de_inicio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turma',
            name='data_de_criação',
        ),
        migrations.AddField(
            model_name='turma',
            name='data_de_criacao',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
